export const SERVICE_CATALOG = [
  { name: 'Medically compromised patient (Extraction per Tooth)', price: 3000.0 },
  { name: 'Deciduous Tooth', price: 1500.0 },
  { name: 'Impacted / Surgical Removal of Tooth', price: 15000.0 },
  { name: 'Frenectomy / Epulis removal + Biopsy', price: 7000.0 },
  { name: 'Hard Tissue Pre-Prosthetics Surgery ( Alveolectomy) Per Quadrant', price: 7000.0 },
  { name: 'Simple e-nucleation of Cyst under GA', price: 28000.0 },
  { name: 'Apicectomy per tooth (Add 2000/- for additional adjoining tooth)', price: 8000.0 },
  { name: 'Surgical Splinting of Sub Luxated Teeth (per arch)- less cost of splint', price: 10000.0 },
  { name: 'Treament of Fracture Reduction / Fixation U/L Jaw with IMF', price: 28000.0 },
  { name: 'Fracture Zygomatic Bone close reduction', price: 21000.0 },
  { name: 'Oral Sub mucus Fibrosis - Excision of band & Repair with Flap per side', price: 42000.0 },
  { name: 'Symptotic hard ware removal per plate', price: 10500.0 },
  { name: 'Fat Grafting', price: 42000.0 },
  { name: 'Skin Grating', price: 20000.0 },
  { name: 'TMJ surgical treatment complete under GA', price: 35000.0 },
  { name: 'Botox injection (less cost of injection)', price: 14000.0 },
  { name: 'Removal of Occlusal / AFID splints LA', price: 3500.0 },
  { name: 'Trans osseous wires removal', price: 7000.0 },
  { name: 'Acrylic per unit (Denture)', price: 5500.0 },
  { name: 'Metal Crown per unit', price: 14000.0 },
  { name: 'Crown Metal Porcelain bonded per unit', price: 17500.0 },
  { name: 'Ceramic crown conventional per unit', price: 28000.0 },
  { name: 'Ceramic veneer conventional per unit', price: 28000.0 },
  { name: 'Prefabricated Aluminum crown per unit', price: 5500.0 },
  { name: 'Removal of crown/PFD by sectioning per unit', price: 2800.0 },
  { name: 'Ceramic repair per unit', price: 4200.0 },
  { name: 'Screw retained crown (PFM) per unit', price: 21000.0 },
  { name: 'Screw retained crown (Zircona) per unit', price: 42000.0 },
  { name: 'C.C Plate (Cast metal dentures Chrome Cobalt per arch)', price: 35000.0 },
  { name: 'Clasp for cast partial denture (per clasp)', price: 2800.0 },
  { name: 'Non precious metal per arch (Full metal)', price: 10000.0 },
  { name: 'Non precious metal with porcelain bonding', price: 16700.0 },
  { name: 'Upper and Lower complete dentures (full set)', price: 58000.0 },
  { name: 'Relining/Rebasing of complete dentures ( upper or lower ) for one denture', price: 3500.0 },
  { name: 'Polishing of dentures', price: 2000.0 },
  { name: 'Obturator (Acrylic)', price: 19600.0 },
  { name: 'Obturator with cast frame', price: 35000.0 },
  { name: 'Cast and welded splint', price: 28000.0 },
  { name: 'Cast split', price: 33500.0 },
  { name: 'Hard relining of complete/partial dentures (per one)', price: 7000.0 },
  { name: 'Rebasing per one denture', price: 14000.0 },
  { name: 'Soft denture relining', price: 3500.0 },
  { name: 'Chairside hard relining', price: 4200.0 },
  { name: 'CAD/CAM crown porcelain', price: 42000.0 },
  { name: 'CAD/CAM crown zirconia', price: 42000.0 },
  { name: 'CAD/CAM inlay/onlay (Zirconia + Cermanic)', price: 41000.0 },
  { name: 'CAD/CAM veneer (Zirconia + Ceramic)', price: 42000.0 },
  { name: 'Implant abutment CAD/CAM', price: 28000.0 },
  { name: 'CAD/CAM bridge framework per unit', price: 19600.0 },
  { name: 'Permanent silicon soft denture lining per arch', price: 14000.0 },
  { name: 'CAD/CAM Inlay (Zirconia + Cermanic)', price: 35000.0 },
  { name: 'Extra oral prosthesis - Ear/Nose/Eyes', price: 91000.0 },
  { name: 'Occlusal equilibriation', price: 8500.0 },
  { name: 'Telescopic crown per unit', price: 11000.0 },
  { name: 'PFM Crown with pink porcelain (per unit)', price: 21000.0 },
  { name: 'Ceramic crown with pink porcelain (conventional)', price: 35000.0 },
  { name: 'Dental Implant (simple) excluding material charges', price: 49000.0 },
  { name: 'Ridge augmentation for future implant placement with bone block graft', price: 28000.0 },
  { name: 'Direct Sinus Lift open (per tooth site) without material', price: 21000.0 },
  { name: 'Implant abutment placement (procedure charges only) cost of implant will be additional', price: 5600.0 },
  { name: 'Healing implant abutment placement (procedure charges only) cost of implant will be additional', price: 5600.0 },
  { name: 'Angled implant abutment placement (procedure charges only) cost of implant will be additional', price: 5600.0 },
  { name: 'Compound Restoration Amalgam (Two/More Surfaces)', price: 4000.0 },
  { name: 'Composite Restoration Anterior', price: 4000.0 },
  { name: 'Composite Restoration Posterior (One Surface)', price: 4000.0 },
  { name: 'Glass ionomer Restoration', price: 4000.0 },
  { name: 'Composite Veneering per tooth', price: 8000.0 },
  { name: 'RCT Premolar without restoration without endo post', price: 10000.0 },
  { name: 'RCT 1st molar without restoration without endo post', price: 12000.0 },
  { name: 'Charges of endo post per root (metal post)', price: 3000.0 },
  { name: 'Charges of endo post per root (Fiber Post)', price: 4000.0 },
  { name: 'Temporary Filling/ Minor gum treatment /Socket dressing/ Sensitive teeth dressing, Cavity Dressing', price: 2000.0 },
  { name: 'Pulpotomy permanent tooth', price: 6000.0 },
  { name: 'RCT Deciduous Tooth Pulpectomy/ Pulpotomy', price: 6000.0 },
  { name: 'Core build up without endo post', price: 4000.0 },
  { name: 'Occlusal View', price: 1000.0 },
  { name: 'Adjustment of Orthodontic Appliance (Removable)', price: 1000.0 },
  { name: 'Repair of Ortodontic Appliances (Removable)', price: 2000.0 },
  { name: 'Oral Screen / Habit Trainer (Hard Acrylic)', price: 10000.0 },
  { name: 'Bite Plane / Inclined Plane (Removable)', price: 3000.0 },
  { name: 'Replacement of Single Bracket or Band', price: 2000.0 },
  { name: 'De-bonding of Fix Ortho Appliance both Arches', price: 10000.0 },
  { name: 'Simple Extraction Per Tooth', price: 2000.0 },
  { name: 'Simple Extraction followed by SR', price: 5000.0 },
  { name: 'Tooth transplant / Replant / Auto transplant', price: 11000.0 },
  { name: 'Simple e-nucleation of Cyst under LA', price: 20000.0 },
  { name: 'E-nucleation including Nasal Antrostomy', price: 30000.0 },
  { name: 'Dressing Cyst/cyst cavity, subsequent visit', price: 1500.0 },
  { name: 'Minor Oral Surgical procedure under local anesthesia', price: 6000.0 },
  { name: 'Salivary Gland (Stone Removal) under LA', price: 10000.0 },
  { name: 'Salivary Gland (repair of duct)', price: 14000.0 },
  { name: 'Oro-antral fistula under LA', price: 14000.0 },
  { name: 'Incision / drainage of abscess under LA', price: 4500.0 },
  { name: 'Coronidectomy per side', price: 16000.0 },
  { name: 'Postoperative Follow up per visit (Major Surgical procedures only)', price: 1000.0 },
  { name: 'Replacement of dressing BIPP', price: 1500.0 },
  { name: 'Alveolar bone grafting unilateral', price: 20000.0 },
  { name: 'Pre-Anesthesia consulatation', price: 1200.0 },
  { name: 'Monitored Care anesthesia', price: 4000.0 },
  { name: 'Prefabricated steel crown per unit', price: 6000.0 },
  { name: 'One tooth acrylic denture', price: 3000.0 },
  { name: 'For every additional tooth', price: 1000.0 },
  { name: 'Cementation of bridge/crown per unit', price: 2000.0 },
  { name: 'Acrylic stent/Splint (Hard)', price: 20000.0 },
  { name: 'Acrylic stent/Splint (Soft)', price: 20000.0 },
  { name: 'Socket preservation after extraction excluding material charges', price: 15000.0 },
  { name: 'Gingival De-pigmentation surgical treatment (per quadrant)', price: 15000.0 },
  { name: 'Indirect Sinus Lift closed technique (per tooth site without material)', price: 10000.0 },
  { name: 'Gingival augmentation (Perioplastic surgery) per Tooth with connective tissue graft', price: 20000.0 },
  { name: 'Tooth exposure for orthodontic trearment', price: 7000.0 },
  { name: 'Crown lengthening (per tooth) with osseous surgery', price: 10000.0 },
  { name: 'Laser periodontal treatment per session', price: 20000.0 },
  { name: 'Composite Restoration Posterior (Two/More Surfaces)', price: 5000.0 },
  { name: 'Use / Application of Bioceramic Material for restorative work', price: 15000.0 },
  { name: 'TPA / LLA / Quad Helix / Blue Grass Appliance Insertion', price: 11500.0 },
  { name: 'Tongue Crib / TPA / LLA / Nance / Quad Helix / Blue Grass Appliance Removal', price: 2000.0 },
  { name: 'Erverdi Plate', price: 20000.0 },
  { name: 'MSE / Fixed Functional appliance (Procedure Charges )', price: 10000.0 },
  { name: 'NiTi Coil Spring', price: 2000.0 },
  { name: 'Bite Turbos per tooth', price: 2000.0 },
  { name: 'Hyrax (banded / bonded / Niti Expander)', price: 20000.0 },
  { name: 'Hyrax Removal', price: 4000.0 },
  { name: 'Fixed Anterior Bite Plane / Inclined Plane Removal', price: 4000.0 },
  { name: '2x4 and 2x6 Appliance Fixed Orthodontics including debonding and removal of adhesives', price: 50000.0 },
  { name: 'Single Arch Fixed Orthodontics', price: 70000.0 },
  { name: 'Single Arch debonding', price: 5000.0 },
  { name: 'Post debonding adhesive removal single arch', price: 3500.0 },
  { name: 'Case Transfer (Incoming CNE)', price: 100000.0 },
  { name: 'Per unit fixed retainer repair maxillary arch', price: 4000.0 },
  { name: 'Per unit fixed retainer repair mandibular arch', price: 2500.0 },
  { name: '2nd molar band', price: 3000.0 },
  { name: '3rd molar band', price: 4000.0 },
  { name: 'Face Bow Transfer', price: 15000.0 },
  { name: 'Orthodontic splint per arch of all kinds (orthognathic, TMJ, deprogramming, repositioning, etc.)', price: 20000.0 },
  { name: 'Addition/ Repair Soldered attachments for Facemask per side', price: 1000.0 },
  { name: 'TADS (per TAD) (Procedure Charges)', price: 5000.0 },
  { name: 'Cheilorraphy', price: 30000.0 },
  { name: 'Palatoraphy', price: 30000.0 },
  { name: 'Tumor resection Surgery', price: 50000.0 },
  { name: 'Tumor Surgery with Hemi-mandiblectmoy', price: 120000.0 },
  { name: 'Tumor Surgery with Hemi-manxillectomy', price: 80000.0 },
  { name: 'Bone Grating with Chin Graft', price: 20000.0 },
  { name: 'Bone Grating with Illiac Graft/ Rib', price: 30000.0 },
  { name: 'Orthognathic surgery (Maxilla)', price: 100000.0 },
  { name: 'Orthgnathic surgery (Mandible)', price: 100000.0 },
  { name: 'Segmental osteotomy maxilla', price: 100000.0 },
  { name: 'Segmental osteotomy mandible', price: 100000.0 },
  { name: 'Genio plasty', price: 45000.0 },
  { name: 'Augmentation Genio plasty', price: 60000.0 },
  { name: 'Alveolar Ridge Augmentation less cost of alloplastic graft material per quadrant', price: 30000.0 },
  { name: 'Neurectomy IO + Mental', price: 10000.0 },
  { name: 'Nerve Avulsion Infereior Alveolar', price: 30000.0 },
  { name: 'Mid face Fracture via coronal flap/ Hemi Coronal flap', price: 50000.0 },
  { name: 'Isolated condyle fracture open reduction per side (less cost of implant)', price: 40000.0 },
  { name: 'Fracture Zygomatic maxillary complex open reduction', price: 50000.0 },
  { name: 'Salivary gland (stone removal) under GA', price: 20000.0 },
  { name: 'Salivary gland (Sublingual gland removal) under GA', price: 20000.0 },
  { name: 'Salivary gland (Submandibular gland removal) under GA', price: 50000.0 },
  { name: 'Salivary gland (Parotid gland removal) under GA', price: 80000.0 },
  { name: 'Distractor Placement (Less Cost of distractor)', price: 80000.0 },
  { name: 'Distractor Removal', price: 20000.0 },
  { name: 'Repair / Closure of Oro-antral fistula under GA Mesh, plate', price: 25000.0 },
  { name: 'Masseter muscle myotomy per side', price: 30000.0 },
  { name: 'Masseter muscle myotomy along with bone contouring per side', price: 50000.0 },
  { name: 'Marsupialization of cystic lesion under GA', price: 20000.0 },
  { name: 'Rhinoplasty / nose aesthetic Surgury', price: 70000.0 },
  { name: 'Supera omohyoid neck Dissection', price: 100000.0 },
  { name: 'Modified / Radical Neck Dissection', price: 150000.0 },
  { name: 'Incision / drainage of abscess under GA', price: 20000.0 },
  { name: 'Ankylosis of TMJ with interpositional arthro plasty (each side)', price: 65000.0 },
  { name: 'TMJ Arthrocentesis per side', price: 10000.0 },
  { name: 'Neuro toxic Alcohol / Glycerol Injection (Less cost of injection)', price: 5000.0 },
  { name: 'Intra-lesional Injection steroid (Less cost of injection)', price: 5000.0 },
  { name: 'Digital smile design only - less prosthesis charges (only software use)', price: 10000.0 },
  { name: 'Study cast', price: 3000.0 },
  { name: 'Conventional wax mock up', price: 6000.0 },
  { name: 'Complete overdenture U/L both', price: 60000.0 },
  { name: 'Complete overdenture U/L (High impact) per additional tooth', price: 60000.0 },
  { name: 'Procedural Charges for Implant supported / retained Prothsis', price: 15000.0 },
  { name: 'Implant Crown insertion (Procedure charges only)', price: 5600.0 },
  { name: 'Surgical Implant complication handling per implant', price: 15000.0 },
  { name: 'Temporary implant abutment placement (procedure charges only)', price: 10000.0 },
  { name: 'Peri implant mucositis debridement per implant', price: 8000.0 },
  { name: 'Periimplantitis debridement with flap relection surgery', price: 15000.0 },
];

